KillerCodeMonkey/ngx-quill

- bundles/index.js
- bundles/ngx-quill.umd.js
- src/quill-editor.component.ts
Min-height and padding were not desired for my use case. The style property was making the ql-container too large.
```typescript
@Component({
...
...
styles: [`
.ql-container .ql-editor {
min-height: 200px;
padding-bottom: 50px;
}
`],
...
})
```
bubble.css and snow.css themes already have height of 100%
```css
.ql-container {
box-sizing: border-box;
font-family: Helvetica, Arial, sans-serif;
font-size: 13px;
height: 100%;
margin: 0px;
position: relative;
}
```
> Removed styles property

- src/quill-editor.component.ts
This was modified to squelch errors/warnings in webpack based project using at-loader.
> lint: remove unused parameters and imports

- src/quill-editor.component.ts
Changed the variable module to type 'any' to fix a problem when running a linter
Element implicitly has an 'any' type because type 'Object' has no index signature.
> Added type to variable modules

- src/quill-editor.component.ts
The bounds option is needed during the contractor for the bubble theme.
> Fix: add bounds option in Quill construtor

- src/quill-editor.component.ts
this change gives us the power to manipulate the value which is passed to the formcontrol
the default behavior didn't change. Set/Get is HTML. But if you use own Blots, the HTML conversion doesn't really work well.
eg of usage:
IN TS:
`
getQuillValue(quill, elementRef) {
return JSON.stringify(quill.getContents());
}
setQuillValue(quill, value) {
try {
return JSON.parse(value);
} catch (err) {
return '';
}
}
`
IN HTML:
`<quill-editor [formControl]="formControl" [valueGetter]="getQuillValue" [valueSetter]="setQuillValue"></quill-editor>`
> added ability to use a value getter/setter for formcontrol

- src/quill-editor.component.ts
fixes #159
Even with `if (isPlatformServer(this.platformId))`, SSR doesn't work because loading quill via `import * as Quill from 'quill'` runs code which calls `document` directly (and throws an error).
This change instead loads quill dynamically only on the browser side. I'm not familiar enough with JS modules to know what affect, if any, using `require('quill')` vs `import 'quill'` will have on tree shaking / optimizing code.
> upd: SSR compatibility

- src/quill-editor.component.spec.ts
- src/quill-editor.component.ts
- src/quill-editor.interfaces.ts
- src/quill.module.ts
Regarding the following request I added the support with minimal update by using module forRoot pattern. 
One can use the global config by 
`QuillEditorModule.forRoot(config)`
at app.module.ts
Related issue/enhancement:
Define global config #171
> Optional global config

- index.ts
- src/quill-editor.component.ts
- src/quill-editor.interfaces.ts
- src/quill.module.ts
(1) correctly set the default module config value; 
(2) use injection token for ModuleWithProviders;
(3) export QuillConfig interfaces
This pull request has locally run through "pretest" and "test".
> fix: correctly set the default module config value; use injection token.

- package.json
According to the (Angular docs](https://angular.io/guide/quickstart#nodejs), Node 8+ is still supported. I don't know if you're relying on Node 10 specific code, you you should consider modifying it to support Node 8. This flag prevents `yarn` from installing `ngx-quill` without Node 10+.
> Require Node >= 8

- src/quill-editor.interfaces.ts
The properties `color`, `background`, `align` and `font` in `QuillToobarConfig` has so far only accepted arrays of strings, making them dropdowns. Sometimes, you want to show the different options directly on the toolbar instead of requiring the user to open a dropdown with the options. For instance, you may want to show all the `align` buttons directly on the toolbar. 
So instead of writing this, which would result in a dropdown with 4 options
`[{ 'align': ['', 'center', 'right', 'justify' ]}]`
You would write this, which would lead to 4 buttons showing in the toolbar
`[{ 'align': '' }, { 'align': 'center' }, { 'align': 'right' }, { 'align': 'justify' }]`
This is actually supported in Quill, but the typescript definition in this file doesn't accept it, so you will get a compile error …
> QuillToolbarConfigs with buttons and dropdown

- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
Fixed #1149
I also added a Custom link placeholder and the option to compare the values in the writeValue function to minimize dom interaction.
Link placeholder and the compare functions are disabled by default, but can be enabled via inputs.
> Execute value setter during init

- README.md
- projects/ngx-quill/src/lib/quill-view.component.spec.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
Hi, 
As discussed in this [issue ](https://github.com/KillerCodeMonkey/ngx-quill/issues/1165) 
Here is an addition of `onEditorCreated` method to `quill-view` component as it's made in `quill-editor` component
Tell me if I should change or add something.
> Add onEditorCreated method to quill-view component

- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill.service.ts
See code comments, that won't bring any breaking change but will only improve the app performance since Quill added event listeners won't cause many change detections to run.
> perf: unpatch `document.addEventListener` when the `quill` is imported

- projects/ngx-quill/package.json
- projects/ngx-quill/tsconfig.lib.prod.json
Since Angular 13 has removed the View Engine support we can now switch to the partial compilation to accommodate with APF (Angular Package Format).
> https://angular.io/guide/angular-package-format#partial-compilation
This's a breaking change and might be published as a major version (`ngx-quill@16`).
> feat: support new Angular Package Format

- .eslintrc.json
- projects/ngx-quill/package.json
- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill-editor.interfaces.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
- projects/ngx-quill/src/lib/quill.service.ts
Hey, I've added an ability to load `customModules` on demand. E.g., if they don't have to be included into the bundle until the editor is rendered.
- Updated `.eslintrc.json` to exclude linting `Quill` argument (because it's not camelCase'd).
> feat: allow custom modules to be loaded on demand

- projects/ngx-quill/config/src/quill-editor.interfaces.ts
Right now, `syntax` module is of type **boolean**.
While that works, we are required to insert `highlight.js` library in the `index.html` so Quill can work properly. The actual typings for `syntax` should be `boolean` or `object`:
```
syntax?: boolean | object;
```
This is because Quill internally uses object for the `syntax`, where the object will have `highlight` property, which is a function. This can be leveraged in order to use `highlight.js` inside the module, and not globally, which would increase the performance in case of lazy-loaded modules.
**Example:**
```typescript
import hljs from 'highlight.js/lib/common';
...
config = {
syntax: {
highlight: (text: string) => hljs.highlightAuto(text).value,
},
};
```
```html
<quill-editor [modules]="config"></quill-editor>
```
This will …
> #1633 Updating typings for "syntax" module

- package.json
- projects/ngx-quill/src/lib/helpers.spec.ts
- projects/ngx-quill/src/lib/helpers.ts
- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill-view-html.component.spec.ts
- projects/ngx-quill/src/lib/quill-view-html.component.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
This commit switches inputs to signal inputs to be compatible with zoneless change detection because everything should be a signal primitive. As such, its changes may be caught by the execution context. Every time a signal changes, it would schedule a change detection event, even in zoneless mode.
I didn't update `@Output()` to `output` because we still use `.observed` properties.
> feat: switch to signal inputs

- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
A regression was spotted by our team when updating to the lastest ngx-quill version, where required form controls applied on quill editors were no longer be marked invalid when emptied.
It looks like `getSemanticHTML()` can return `<p></p>` when the editor is emptied (at least when it is emptied programatically using `setText('')`). This commit augments the "empty" check to handle this possible value and `<div></div>`. A unit test has been added to reproduce this issue.
> fix: handle empty value returned by getSemanticHTML

- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
There currently is an issue where if you have custom `formats` (I had `formats: ['link', 'size', 'italic', 'bold', 'list', 'header', 'underline', 'indent', 'align', 'color', 'image', 'strong'],`) configured in the `QuillModule.forRoot()` method and you don't pass in custom `formats` to the view component. This throws the following runtime error when trying to render `<quill-view />`:
```
TypeError: formats.forEach is not a function at createRegistryWithFormats (createRegistryWithFormats.js:10:11)
```
This is because the `formats` that's passed into `Quill` from the `QuillViewComponent` component can be an object, as opposed to a `string[]`, when `formats` passed into the component is `undefined` (see line [143](https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/sr …
> Fix QuillViewComponent formats issue

- projects/ngx-quill/config/src/quill-editor.interfaces.ts
- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
Hi, I found beforeRender only accept `() => Promise<void>`, but in my use case, I have to render quill after every async sources loaded, beforeRender maybe just need a resoved status instead of specific `void` type
> fix: beforeRender accpet return type Promise<any>

- projects/ngx-quill/src/lib/quill-editor.component.ts
We should manually remove event listeners to prevent memory leaks.
> fix: remove event listeners when component is destroyed

- projects/ngx-quill/config/src/quill-editor.interfaces.ts
- projects/ngx-quill/src/lib/quill-editor.component.spec.ts
- projects/ngx-quill/src/lib/quill-editor.component.ts
- projects/ngx-quill/src/lib/quill-view.component.ts
- projects/ngx-quill/src/lib/quill.service.ts
In this commit, we introduce a slightly smarter approach to handling custom module registration and executing the `beforeRender` function. The current issue is that the `quill-editor-toolbar` may be projected before the editor is rendered due to the `Promise.all` in `mergeMap`. This is noticeable on slower devices, where the toolbar appears first (without styles), and then after a microtask delay, Quill is created.
Switching to observables resolves this issue because observables can emit both synchronously and asynchronously, and most observables can cache their emissions using `shareReplay`, ensuring that subsequent emissions are always synchronous.
> fix: reduce asynchronous stuff to resolve flickering
